### ISSUE TITLE
Add kebab case

### ISSUE THREAD

**Issue by phoe** [EuAndreh/cl-slug#2]
The `kick-me-baby-one-more-time` case is also known as kebab-case - I would add this term to the readme so it is indexed by e.g. search engines.

http://wiki.c2.com/?KebabCase
http://stackoverflow.com/questions/11273282/whats-the-name-for-hyphen-separated-case/12273101

**Comment by EuAndreh** [comment]
Sure, that's a good idea.

Maybe a function for each style, like in [Clojure's camel-snake-kebab](https://github.com/qerub/camel-snake-kebab)?

**Comment by phoe** [comment]
Why not, sure thing.
