### ISSUE TITLE
Why is add-language a macro ? (on reddit)

### ISSUE THREAD

**Issue by vindarel** [EuAndreh/cl-slug#3]
Hi there !

your lib is having its time on reddit https://www.reddit.com/r/Common_Lisp/comments/67neph/clslug_slugify_uris_camelcase_remove_accentuation/
there are good remarks there, for example about add-language not needing to be a macro (they say).

great lib btw :) 

ps: you've also be added on cliki: http://www.cliki.net/cl-slug

**Comment by EuAndreh** [comment]
That's a valid point.

I should improve this in the weekend. I'll ping you when I do.

https://www.reddit.com/r/Common_Lisp/comments/67neph/clslug_slugify_uris_camelcase_remove_accentuation/dgsjovh/
