### ISSUE TITLE
Italian accents

### ISSUE THREAD

**Issue by priyadarshan** [EuAndreh/cl-slug#4]
Hi,

Right now the Italian section has

```
(add-language "Italiano (Italian)" :it
              ((e . è) (o . ò) (i . î)
               (e . é) (o . ó)))
```

As far as I know, the only vowel to have a "closed" sound in Italian language is `e`, marked `è` and `é`.

- The `î` should be `ì`
- They have also `à` and `ù`. (Similarly to the above, `á` and `ú`would be a mistake.)

So, if I understand the code correctly, it should probably be:

```
(add-language "Italiano (Italian)" :it
              ((e . è) (o . ò) (i . ì)
               (e . é) (o . ó) (a . à) (u . ù))
```

To follow the classical vowel sequence, as used in textbooks, `aeiou`, it could more cleanly be:

```
(add-language "Italiano (Italian)" :it
              ((a . à) (e . è) (e . é)
               (i . ì) (o . ò) (o . ó) (u . ù))
```

Edit: My apology, Italian does have `ó`, (http://sites.psu.edu/symbolcodes/languages/psu/italian/). I have edited the above.

**Comment by priyadarshan** [comment]
Edit: My apology, Italian does have `ó`, (http://sites.psu.edu/symbolcodes/languages/psu/italian/). I have edited the above.

**Comment by EuAndreh** [comment]
Closing stale issue. Patches welcome :)

**Comment by priyadarshan** [comment]
Thanks, I will submit a patch if I can muster some Common Lisp knowledge.

Thanks for keeping this open so long. 👍
